NET Moodle/Models/NewsViewModel.cs
using NET_Moodle.Domain.Model;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NET_Moodle.Models
{
    public class NewsViewModel
    {
        [Display(AutoGenerateField = false)]
        public int NewsId { get; set; }

        [Display(Name = "Tytuł")]
        [Required(ErrorMessage = "Podaj tytył newsa")]
        public string Title { get; set; }

        [Display(Name = "Opis")]
        [Required(ErrorMessage = "Podaj opis newsa")]
        public string Description { get; set; }

        [Display(Name = "Data")]
        [Required(ErrorMessage = "Podaj date dodania")]
        public DateTime CreationDate { get; set; }

        [Display(AutoGenerateField = false)]
        public string ImagePath { get; set; }

        [Display(Name = "Powiązane")]
        [Required(ErrorMessage = "Podaj id prelegenta")]
        public int LecturerId { get; set; }

        public static NewsViewModel ToNewsViewModel(News news)
        {

            return new NewsViewModel()
            {
                Title = news.TopicName,
                Description = news.Description,
                CreationDate = news.CreationDate,
                ImagePath = news.Image.ImagePath,
                LecturerId = news.LecturerId,
                NewsId = news.NewsId
            };
        }
    }
}

NET Moodle/Controllers/NewsController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using NET_Moodle.Domain.Interfaces;
using NET_Moodle.Domain.Model;
using NET_Moodle.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NET_Moodle.Controllers
{
    public class NewsController : Controller
    {
        private INews _newsRepository;
        private ILecturer _lecturerRepository;
        public NewsController(INews newsRepository, ILecturer lecturerRepository)
        {
            _newsRepository = newsRepository;
            _lecturerRepository = lecturerRepository;
        }

        public ActionResult Index()
        {
            return View();
        }
        // GET: News
        [Authorize(Roles ="Admin")]
        public ActionResult ManageNews()
        {
            var News = _newsRepository.Get().ToList();
            var NewsViewModels = News.Select(n => { return NewsViewModel.ToNewsViewModel(n); }).ToList();
            return View(NewsViewModels);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ActionResult CreateNews()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult CreateNews(NewsViewModel newsViewModel, HttpPostedFileBase file)
        {

            //newsViewModel.LecturerId = _lecturerRepository.GetByUserId(userId).LecturerId;
            if (!ModelState.IsValid || file == null)
            {
                return View(newsViewModel);
            }
            string targetFolder = Server.MapPath("~/Content/Images");
            string targetPath = Path.Combine(targetFolder, file.FileName);
            file.SaveAs(targetPath);

            Image image = new Image
            {
                AlternateString = file.FileName,
                ImagePath = file.FileName,
            };
            var userId = User.Identity.GetUserId();
            News news = new News()
            {
                CreationDate = DateTime.Now,
                LecturerId = _lecturerRepository.GetByUserId(userId).LecturerId,
                Description = newsViewModel.Description,
                Image = image,
                PhotoName = file.FileName,
                TopicName = newsViewModel.Title

            };

            _newsRepository.Add(news);


            return RedirectToAction("ManageNews");
        }

        [Authorize(Roles = "Admin")]
        public ActionResult DeleteNews(int newsId)
        {
            _newsRepository.DeleteById(newsId);
            return RedirectToAction("ManageNews");
        }



    }
}

NET Moodle/Views/News/CreateNews.cshtml
@model NET_Moodle.Models.NewsViewModel

@{
    ViewBag.Title = "CreateNews";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="form-horizonta well col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4">
        <div class="text-center">
            <h2>Dodaj wiadomość</h2>
        </div>
        @using (Html.BeginForm("CreateNews","News",FormMethod.Post, htmlAttributes: new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Description,  new { @class = "form-control" })
                        <span class="help-block"></span>
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label for="file" class="col-md-2 control-label">Zdjęcie</label>
                    <div class="col-md-10">
                        <input type="file" accept="image/x-png, image/gif, image/jpeg" id="file" name="file">
                        <input type="text" readonly="" class="form-control" placeholder="Wybierz plik...">
                    </div>
                </div>

              
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Dodaj" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

    </div>
</div>

NET Moodle/Views/News/ManageNews.cshtml
@model IEnumerable<NET_Moodle.Models.NewsViewModel>

@{
    ViewBag.Title = "ManageNewsView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-1 col-lg-1 col-xs-1"></div>
    <div class="col-md-10 col-lg-10 col-xs-10">
        <div class="well">
            <div class="row">
                <div class="col-md-1 col-lg-1 col-xs-1"></div>
                <div class="col-md-10 col-lg-10 col-xs-10">
                    <div class="row">
                        <h2>Wiadomości</h2>
                        <p>
                            <a href="javascript:void(0)" class="btn btn-raised btn-primary btn-xs main-background-color"><i class="material-icons">create</i> Dodaj</a>
                        </p>

                        <div class="input-group">
                            <input id="filter" type="text" class="form-control" placeholder="Type here...">
                        </div>
                        <table class="table table-striped table-hover ">
                            <thead>
                                <tr style="background-color: #3F729B; color: white; " class="table-default-style">
                                    <th>Tytuł</th>
                                    <th style="width:25%">Opis</th>
                                    <th>Data utworzenia</th>
                                    <th>Akcje</th>
                                </tr>
                            </thead>
                            <tbody class="searchable">
                                @foreach (var item in Model)
                                {
                                    <tr class="table-default-style">
                                        <td class="table-css">@item.Title</td>
                                        <td class="table-css table-css-ellipsis">@item.Description</td>
                                        <td class="table-css">@item.CreationDate.ToShortDateString()</td>
                                       
                                        <td class="table-css">
                                            <span style="padding-right:0"><a class="material-icons main-color hover-icon">mode_edit</a><a class="material-icons main-color hover-icon">block</a><a class="material-icons main-color hover-icon" onclick="openModal(@item.NewsId)">delete_sweep</a>  </span>

                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="DeletePopup" class="modal fade" role="dialog">
    <div class="modal-dialog modal-sm">
        @using (Html.BeginForm("DeleteNews", "News", FormMethod.Post))
        {
            <input type="hidden" id="element-to-delete" name="newsId"/>
        <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" tabindex="3">&times;</button>
                    <h4 class="modal-title">Potwierdzenie akcji</h4>
                </div>
                <div class="modal-body">
                    <p>Czy na pewno chcesz usunąć ten kurs?</p>
                </div>
                <div class="modal-footer" style="text-align:center">
                    <!-- to center or not to center? -->
                    <button type="button" class="btn btn-default" data-dismiss="modal" tabindex="1">Nie</button>
                    <input type="submit" class="btn btn-default" value="Tak" />
                </div>
            </div>
        }
    </div>
</div>