NET Moodle/Controllers/AuthorController.cs
using NET_Moodle.Domain.Interfaces;
using NET_Moodle.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NET_Moodle.Controllers
{
    [RoutePrefix("Authors")]
    public class AuthorController : Controller
    {
        private IAuthor authorRepository;
        public AuthorController(IAuthor authorRepository)
        {
            this.authorRepository = authorRepository;
        }
        // GET: Author
        [Route("")]
        public ActionResult Index()
        {
            var authors = authorRepository.Get().ToAuthorViewModel();
            return View(authors);
        }
    }
}

NET Moodle/Views/Shared/LoggedUserPartial.cshtml
@using Microsoft.AspNet.Identity

<nav class="navbar navbar-fixed-top z-depth-1 top-nav-collapse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("NET Moodle", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul id="nav1" class="nav navbar-nav waves-effect">
                <li>@Html.ActionLink("Partnerzy", "Index", "Company")</li>
                <li>@Html.ActionLink("O nas", "Index", "Lecturer")</li>
                <li>@Html.ActionLink("Kontakt", "Index", "Contact")</li>
            </ul>

            @if (Request.IsAuthenticated)
            {
            using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
            {
            @Html.AntiForgeryToken()

            <ul class="nav navbar-nav navbar-right">

                <li class="dropdown">
                    <a class="hover-icon" id="dropdownMenu1" onclick="getUserCourses('@Url.Action("GetUserCourses","Course",new { id = User.Identity.GetUserId() })')" alt="@User.Identity.GetUserId()" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Moje kursy
                        <span class="caret"></span>
                    </a>
                    <!--MISSING CONTENT HERE-->
                    <ul class="dropdown-menu dropdown-menu-left" id="courses-content"></ul>
                </li>

                    <li>@Html.ActionLink("Użytkownicy", "GetUsers", "UserPanel")</li>

                    <li class="dropdown">
                        <a class="material-icons hover-icon" style="font-size: 30px !important" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">account_circle</a>
                        <ul class="dropdown-menu dropdown-menu-left">
                            <li class="dropdown-header">
                                Zalogowany jako @User.Identity.GetUserName()
                            </li>
                            <li>
                                @Html.ActionLink("Ustawienia konta", "Index", "Manage")
                            </li>
                            <li><a href="javascript:document.getElementById('logoutForm').submit()">Wyloguj</a></li>
                        </ul>
                    </li>

</ul>
            }
            }
            else
            {
            <ul class="nav navbar-nav navbar-right">
                <li>
                    @Html.ActionLink("Rejestracja", "Register", "Account")
                </li>
                <li>@Html.ActionLink("Logowanie", "Index", "UserPanel")</li>
            </ul>
            }


        </div>
    </div>
</nav>

NET Moodle/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>.NET Moodle</title>
    @*<link rel="icon" type="image/png" href="@Url.Content("~/favicon.png")"/>*@

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


    @RenderSection("scripts", required: false)
</head>
<body class="padding-top">
            @Html.Partial("LoggeduserPartial")

    <div class="container-fluid body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="row">
                <div class="col-md-offset-1 col-sm-3 col-lg-1">
                    @Html.ActionLink("Twórcy aplikacji", "Index", "Author")
                </div>
            </div>
            <p>&copy; @DateTime.Now.Year - .NET Moodle PUT Poznań </p>
        </footer>
    </div>

    
</body>
</html>

NET Moodle/Views/Shared/_UserCoursesPartial.cshtml
@model NET_Moodle.Models.CourseViewModel

@{
    var courses = ViewBag.courses;
}

@if (courses.Count == 0)
{
    <li>
        <a class="dropdown-item">Brak</a>
    </li>
}
else
{
    foreach (var item in courses)
    {
        <li>
            <a class="dropdown-item" href="@Url.Action("CourseDetail","Course",new { id = item.CourseId })" alt="@item.CourseId)">@item.ShortCut</a>
        </li>
    }

}