NET Moodle/Models/TopicViewModel.cs
using NET_Moodle.Domain.Model;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NET_Moodle.Models
{
    public class TopicViewModel
    {
        [Display(AutoGenerateField = false)]
        public int Id { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Nazwa", Description = "Nazwa tematu")]
        public string Name { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Opis", Description = "Opis tematu")]
        public string Description { get; set; }

        [Required]
        [Display(Name = "Restrykcje")]
        public bool Restriction { get; set; }

        [DataType(DataType.DateTime, ErrorMessage = "Nieprawidłowa data")]
        [Display(Name = "Data rozpoczęcia ")]
        public DateTime StartDate { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Data utworzenia ")]
        public DateTime CreationDate { get; set; }

        [Display(Name = "Kurs")]
        [Required(ErrorMessage = "Podaj id kursu")]
        public int CourseId { get; set; }

        public static TopicViewModel ToTopicViewModel(Topic Topic)
        {
            return new TopicViewModel()
            {
                Name = Topic.Name,
                Description = Topic.Description,
                CreationDate = Topic.CreationDate,
                StartDate = Topic.StartDate.Value,
                Restriction = Topic.Restriction,
                CourseId = Topic.CourseId
            };
        }
    }
}

NET Moodle/Controllers/TopicController.cs
using NET_Moodle.Domain.Interfaces;
using NET_Moodle.Domain.Model;
using NET_Moodle.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NET_Moodle.Controllers
{
    public class TopicController : Controller
    {

        private ICourse _courseRepository;
        private ITopic _topicRepository;
        public TopicController(ITopic topicRepository, ICourse courseRepository)
        {
            _topicRepository = topicRepository;
            _courseRepository = courseRepository;
        }

        [HttpGet]
        public ActionResult AddTopic()
        {
            return View();
        }

        [HttpPost]
        [Route("Create")]
        public ActionResult AddTopic(TopicViewModel model, int id)
        {
            Topic topic = new Topic
            {
                Name = model.Name,
                Description = model.Description,            
                StartDate = model.StartDate,
                CreationDate = DateTime.Now,
                Restriction = model.Restriction,
                CourseId = id
            };

            _topicRepository.Add(topic);
            return RedirectToAction("CourseDetail","Course",new { id = id });
        }
    }
}

NET Moodle/Views/Topic/AddTopic.cshtml
@model NET_Moodle.Models.TopicViewModel

@{
    ViewBag.Title = "AddTopic";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="form-horizonta well col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">

        @using (Html.BeginForm("AddTopic", "Topic", FormMethod.Post, htmlAttributes: new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Dodawanie tematu</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Restriction, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="checkbox col-md-10 bootstrap-switch-square">
                        <label style="margin-right:15px">
                            <input type="checkbox" data-toggle="switch" value="true" id="Restriction" name="Restriction">
                        </label>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" class="btn btn-info btn-raised default-color" value="Dodaj" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>